pipeline {

 agent any

 environment {

  IMAGE_NAME = "catering-platform"

 }

 stages {

  stage('Clone Code') {

   steps {

    git 'https://github.com/company/catering-platform'

   }

  }

  stage('Build Docker Image') {

   steps {

    sh 'docker build -t $IMAGE_NAME .'

   }

  }

  stage('Push to ECR') {

   steps {

    sh 'docker push $IMAGE_NAME'

   }

  }

  stage('Deploy to Kubernetes') {

   steps {

    sh 'kubectl apply -f kubernetes/'

   }

  }

 }

}
